apiVersion: v1
kind: Namespace
metadata:
  name: production
---
kind: Service
apiVersion: v1
metadata:
  name: lp-prod-service
spec:
  ports:
  - port: 80
    protocol: TCP
    #type: LoadBalancer
  selector:
    app: lp-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lp-prod-deployment
  labels:
    app: lp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lp-prod
      track: stable
  template:
    metadata:
      labels:
        app: lp-prod
        track: stable
    spec:
      containers:
      - name: lp-prod
        image: renardarv/landingpage:buildnumber
        ports:
        - containerPort: 80
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lp-prod-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: lp.renard.my.id
    http:
      paths:
      #- path: /
      - backend:
          serviceName: lp-prod-service
          servicePort: 80
